### ISSUE TITLE
RangeError: Invalid array buffer length

### ISSUE THREAD

**Issue by teenangst** [meteor/tutorials#144]
_Part 1_
I am on the Todo App with Angular and get a `RangeError: Invalid array buffer length` error when running the server before I edit any code.  
I did:  
`meteor create simple-todos`  
`meteor remove blaze-html-templates`  
`meteor add angular-templates`  
`meteor npm install`  
`meteor`  
And I got the error:  

```
[[[[[ C:\Users\Skylark\Documents\!learning\simple-todos ]]]]]

=> Started proxy.
=> Started MongoDB.
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-8qpn3o\web.browser']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-8qpn3o\\web.browser' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1eu41ox\os']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1eu41ox\\os' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-i68f6i']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-i68f6i' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-p3p1ai']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-p3p1ai' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1rtv4yx\os']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1rtv4yx\\os' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-vp7k17']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-vp7k17' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1amtwpw\web.browser']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1amtwpw\\web.browser' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-jprxgj']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-jprxgj' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-3zkkg6']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-3zkkg6' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-ewn0xr']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-ewn0xr' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1cohfxi\web.cordova']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1cohfxi\\web.cordova' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-woxinv\web.browser']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-woxinv\\web.browser' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1ba8iq4\os']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1ba8iq4\\os' }
{ [Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\Skylark\AppData\Local\Temp\mt-1dj14np\web.browser']
  errno: -4051,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: 'C:\\Users\\Skylark\\AppData\\Local\\Temp\\mt-1dj14np\\web.browser' }
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:96:12)
    at new Buffer (buffer.js:56:12)
    at increaseBufferIfNecessary (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:58:23)
    at [object Object]._write (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:65:5)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at [object Object].Writable.write (_stream_writable.js:214:11)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\request\request.js:1255:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
```

________________

_Part 2_
To just start anew I tried to create the project from scratch and got a similar error:

I did:
`meteor create simple-todos`
  
And I got the error:  
```
buffer.js:25
    const ui8 = new Uint8Array(size);
                ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:96:12)
    at new Buffer (buffer.js:56:12)
    at increaseBufferIfNecessary (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:58:23)
    at [object Object]._write (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\stream-buffers\lib\writable_streambuffer.js:65:5)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at [object Object].Writable.write (_stream_writable.js:214:11)
    at Request.ondata (stream.js:31:26)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Skylark\AppData\Local\.meteor\packages\meteor-tool\1.4.0-1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\request\request.js:1255:12)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:536:20)
```

What did I do wrong? I was following instructions

**Comment by teenangst** [comment]
I reinstalled and it works, but the issue itself isn't fixed - is it? (I'll let someone who knows more close it)
