### ISSUE TITLE
App crashing on start up

### ISSUE THREAD

**Issue by starman-vlad** [meteor/tutorials#178]
I was following the tutorial from this [link](https://www.meteor.com/tutorials/blaze/creating-an-app) and I am not able to run the app.
This occurs on:
 - Ubuntu 18.04
 - Windows 10 April 2018 Update

The error log:
```bash
➜  simple-todos meteor
[[[[[ ~/Desktop/simple-todos ]]]]]            

=> Started proxy.                             
=> Started MongoDB.                           
W20180805-14:33:34.912(2)? (STDERR) /home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:475
W20180805-14:33:34.982(2)? (STDERR) }).run();
W20180805-14:33:34.983(2)? (STDERR)    ^
W20180805-14:33:34.983(2)? (STDERR) 
W20180805-14:33:34.984(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180805-14:33:34.984(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180805-14:33:34.984(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180805-14:33:34.984(2)? (STDERR)     at Object.require (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:288:32)
W20180805-14:33:34.985(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
W20180805-14:33:34.985(2)? (STDERR)     at require (packages/modules-runtime.js:244:16)
W20180805-14:33:34.985(2)? (STDERR)     at livedata_connection.js (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180805-14:33:34.985(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180805-14:33:34.986(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180805-14:33:34.986(2)? (STDERR)     at namespace.js (packages/ddp-client/common/namespace.js:1:300)
W20180805-14:33:34.986(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
=> Exited with code: 1
W20180805-14:33:36.706(2)? (STDERR) /home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:475
W20180805-14:33:36.707(2)? (STDERR) }).run();
W20180805-14:33:36.708(2)? (STDERR)    ^
W20180805-14:33:36.708(2)? (STDERR) 
W20180805-14:33:36.709(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180805-14:33:36.709(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180805-14:33:36.709(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180805-14:33:36.710(2)? (STDERR)     at Object.require (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:288:32)
W20180805-14:33:36.710(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
W20180805-14:33:36.711(2)? (STDERR)     at require (packages/modules-runtime.js:244:16)
W20180805-14:33:36.711(2)? (STDERR)     at livedata_connection.js (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180805-14:33:36.711(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180805-14:33:36.712(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180805-14:33:36.712(2)? (STDERR)     at namespace.js (packages/ddp-client/common/namespace.js:1:300)
W20180805-14:33:36.713(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
=> Exited with code: 1
W20180805-14:33:38.263(2)? (STDERR) /home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:475
W20180805-14:33:38.264(2)? (STDERR) }).run();
W20180805-14:33:38.265(2)? (STDERR)    ^
W20180805-14:33:38.265(2)? (STDERR) 
W20180805-14:33:38.265(2)? (STDERR) Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'
W20180805-14:33:38.266(2)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180805-14:33:38.266(2)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180805-14:33:38.266(2)? (STDERR)     at Object.require (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/boot.js:288:32)
W20180805-14:33:38.267(2)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
W20180805-14:33:38.267(2)? (STDERR)     at require (packages/modules-runtime.js:244:16)
W20180805-14:33:38.267(2)? (STDERR)     at livedata_connection.js (/home/user/Desktop/simple-todos/.meteor/local/build/programs/server/packages/ddp-client.js:147:30)
W20180805-14:33:38.268(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180805-14:33:38.268(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180805-14:33:38.269(2)? (STDERR)     at namespace.js (packages/ddp-client/common/namespace.js:1:300)
W20180805-14:33:38.269(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by starman-vlad** [comment]
Resolved by adding `"@babel/runtime": "7.0.0-beta.55"` to the list of dependencies.

**Comment by jasonsblake** [comment]
Hi Vladimir, would you mind sharing how you did this? Apologies in advance I'm a NOOB.

**Comment by starman-vlad** [comment]
@jasonsblake No worries.

Just change the version of `@babel/runtime` to `7.0.0-beta.55` in `package.json`, then rerun the Meteor app.

And update Meteor to latest version.

**Comment by jasonsblake** [comment]
Thank you!
