### ISSUE TITLE
Creating an App - errors prevented startup...

### ISSUE THREAD

**Issue by AndreLei** [meteor/tutorials#39]
Hi,

I've just started using meteor with Angular and I'm trying to figure out the basic concepts.

I started with this tutorial https://www.meteor.com/tutorials/angular/creating-an-app. And when I entered "meteor" into command line I get the error below:

Started MongoDB.
Errors prevented startup:

While loading plugin compileTemplatesBatch from package templating:
module.js:338:15: Cannot find module '../modules/es6.object.get-own-property-descriptor'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Andraz\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\node_modules\core-js\es6\object.js:12:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (C:\Users\Andraz\AppData\Local.meteor\packages\templating\1.1.7\plugin.compileTemplatesBatch.os\npm\node_modules\meteor\ecmascript-runtime\node_modules\meteor\ecmascript-runtime\node_modules\meteor-ecmascript-runtime\server.js:1:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at npmRequire (C:\tools\isobuild\bundler.js:1665:14)
at Module.useNode (packages/modules-runtime.js:453:20)
at fileEvaluate (packages/modules-runtime.js:157:20)
at require (packages/modules-runtime.js:92:16)
at meteorInstall.node_modules.meteor.ecmascript-runtime.runtime.js (packages/ecmascript-runtime.js:24:18)
at fileEvaluate (packages/modules-runtime.js:158:9)
at require (packages/modules-runtime.js:92:16)
at packages/ecmascript-runtime.js:2832:15
at packages/ecmascript-runtime.js:2845:3

Your application has errors. Waiting for file change.

I am using Win 8.1 OS. Do you have an advice for me?

Cheers, andre.

**Comment by Urigo** [comment]
@DJMKLAPA I've just tested the tutorial and it looks fine.
I tested it on a Mac though..  can you upload your source files and share them so I could have a look?

**Comment by jerolan** [comment]
Same error on WIN10

The file es6.object.get-own-property-descriptor is not in core-js node_modules dependencies
<a href="http://es.tinypic.com?ref=2j465pk" target="_blank"><img src="http://i65.tinypic.com/2j465pk.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Irrelevant** [comment]
I'm getting the same error on windows 10, after updating my meteor install. (the samples were working a few days ago with the previous meteor version)

Files attached
[simple-todos.zip](https://github.com/meteor/tutorials/files/195924/simple-todos.zip)
[meteor errors.txt](https://github.com/meteor/tutorials/files/195949/meteor.errors.txt)

**Comment by Urigo** [comment]
related to https://github.com/meteor/meteor/issues/6609
Closing here and please track the progress and comment on that issue
